### ISSUE TITLE
Create a test PR

### ISSUE THREAD

**Issue by merajmasuk** [merajmasuk/student-information-management-webdev#8]
- [x] Fork this repository
- [x] Clone on a local computer
- [x] Create a directory 'testDir'.
- [ ] Create a file 'testFile' inside 'testDir'
- [ ] git add, git commit and git push
- [ ] Create a pull request from the commit

**Comment by epiprokash** [comment]
I cloned the the repository but the app is not working

**Comment by merajmasuk** [comment]
@epiprokash  Is your issue solved?
